### PR TITLE
Fix CI: stunnel don't start because certs are missing

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by n-rodriguez** [comment]
Ubuntu is broken because of default values for `verifyPeer` and `verifyChain` :

```sh
root@4702d86ca6d9:/etc/stunnel/services.d# /etc/init.d/stunnel4 status
● stunnel4.service - LSB: Start or stop stunnel 4.x (SSL tunnel for network daemons)
   Loaded: loaded (/etc/init.d/stunnel4; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-09-23 22:20:28 UTC; 3s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1075 ExecStart=/etc/init.d/stunnel4 start (code=exited, status=1/FAILURE)

Sep 23 22:20:28 4702d86ca6d9 stunnel4[1075]: [ ] Snagged 64 random bytes from /dev/urandom
Sep 23 22:20:28 4702d86ca6d9 stunnel4[1075]: [ ] PRNG seeded successfully
Sep 23 22:20:28 4702d86ca6d9 stunnel4[1075]: [!] /etc/stunnel/services.d/graphite-server.conf:16: "verifyPeer = yes": Specified option name is not valid here
Sep 23 22:20:28 4702d86ca6d9 stunnel4[1075]: [!] /etc/stunnel/stunnel.conf:14: Failed to include directory "/etc/stunnel/services.d"
```
It works if I remove them from `/etc/stunnel/services.d/graphite-server.conf`.

**Comment by n-rodriguez** [comment]
cc @alxwr

**Comment by n-rodriguez** [comment]
Maybe we should relax default values. It could be the occasion to fix https://github.com/saltstack-formulas/stunnel-formula/issues/6.

**Comment by n-rodriguez** [comment]
It could be done in 3 times : 
1. merge this PR first (because it doesn't change anything in the salt code itself) and it helps to run tests locally
2. add semantic-release
3. fix bugs

**Comment by myii** [comment]
@n-rodriguez I added a commit (9cd995a); if you're not happy with it, please feel free to remove it.

**Comment by n-rodriguez** [comment]
> @n-rodriguez I added a commit ([9cd995a](https://github.com/saltstack-formulas/stunnel-formula/commit/9cd995a974becd539f30a7cfb3d41802a1aac001)); if you're not happy with it, please feel free to remove it.

It looks good to me. thank you! :+1:

**Review by myii — APPROVED** [review]

**Comment by myii** [comment]
@n-rodriguez Thanks, this has been merged.  I did add another small commit (e2f5a95) to fix the commented example in `pillar.example`, from a `yamllint` perspective.

**Pull request merged**
