### PR TITLE
Fix CI: stunnel don't start because certs are missing

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by n-rodriguez** [comment]
I think we can merge this one with https://github.com/saltstack-formulas/stunnel-formula/pull/4 to eventually have a working CI. Then I could add some tests :)

**Comment by myii** [comment]
@n-rodriguez The service still isn't starting in both test runs.  Can you resolve this?

**Comment by n-rodriguez** [comment]
> @n-rodriguez The service still isn't starting in both test runs. Can you resolve this?

To resolve this you need to merge both PR. The first to merge is https://github.com/saltstack-formulas/stunnel-formula/pull/4. Then I will rebase my branch.

**Comment by n-rodriguez** [comment]
I've tested locally. It's just I don't want to lose a contribution neither wait for changes (rebase) on it :)

**Comment by myii** [comment]
@n-rodriguez OK, looking at #4 now.

**Comment by myii** [comment]
@n-rodriguez Unfortunately, I can't merge on this repo because:

* Only those with write access to this repository can merge pull requests.

I'll get this resolved but in the meantime, are you able to merge #4?

**Comment by n-rodriguez** [comment]
> are you able to merge #4?

neither do I, sorry...

**Comment by myii** [comment]
@n-rodriguez OK, I've sent a request in our [Formulas group on Slack](https://saltstackcommunity.slack.com/messages/C7LG8SV54/), which is also linked by IRC and available via. Matrix (e.g. riot.im) -- bridged to `#saltstack-formulas`
on Freenode.  It would be great if you could join us there -- it's far easier to get someone's attention there, too.

**Comment by n-rodriguez** [comment]
> It would be great if you could join us there

sure! :+1:

**Comment by myii** [comment]
@n-rodriguez It occurred to me that I could go ahead and test what would happen once both of these PRs are merged: https://travis-ci.com/myii/stunnel-formula/builds/109055910.  As you can see, one of them is still failing.  Could you look into this?

**Comment by n-rodriguez** [comment]
> As you can see, one of them is still failing. Could you look into this?

Stunnel 5.06 don't support the `include` directive. Services declaration must go in `stunnel.conf` file.

**Comment by n-rodriguez** [comment]
I would say this formula is not compatible with Debian Jessie.

**Comment by myii** [comment]
@n-rodriguez Is there no way to adapt the formula for `< v5.06`?  Or does Jessie need to be removed from the test matrix instead?  If that's the way forward, then probably need a note in the `README` as well.

**Comment by myii** [comment]
@alxwr Any suggestions about how to deal with Jessie based upon the situation above?

**Comment by myii** [comment]
@n-rodriguez We've got write access now so what would you like to do about merging #4 and this PR?

**Comment by daks** [comment]
@n-rodriguez to keep `kitchen.yml` clear and simple, I recommend to put pillar data outside of it, for example in `test/salt/pillar` directory, like done https://github.com/daks/usersandgroups-formula/blob/master/kitchen.yml#L40

**Comment by alxwr** [comment]
> @alxwr Any suggestions about how to deal with Jessie based upon the situation above?

Yes. Work with macros and decide based on `osfinger` where to put their output and whether to use `include`.

Good catch btw.

**Pull request closed without merging**
