### PR TITLE
Adding option to disable automatic certificates configuration generation

### PR DESCRIPTION
**Pull request by campof**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

https://github.com/saltstack-formulas/stunnel-formula/issues/6

### Describe the changes you're proposing

Adding a new option in stunnel:lookup called enable_certificates which can make certificates configuration generation disabled when the service is to be used as a client to another instance of stunnel. The default value is set to true as to not change the standard behavior of the formula

### Pillar / config required to test the proposed changes

```
stunnel:
  lookup:
    enable_certificates: false
  config:
    services:
      graphite-server:
        client: 'no'
        accept: '12003'
        connect: '127.0.0.1:2003'
        debug: notice
        checkHost: myhostname
        checkIP: 192.168.0.1
      graphite-client:
        client: 'yes'
        accept: '127.0.0.1:2003'
        connect: '127.0.0.1:12003'
        verifyChain: 'yes'
        verifyPeer: 'yes'
```

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by campof** [comment]
Hello ! 
I would like some help about this PR.
I think it's ok modifications wise in the code, but i do not really know where should i start to implement some pertinent testing about this change, and where to edit the documentation (I already updated the pillar.example)

**Review by daks — APPROVED** [review]
Looks good to me, thanks

**Comment by baby-gnu** [comment]
I approved the CI run but has some failures

**Comment by daks** [comment]
@campof once commits are squashed together, I can merge it

**Comment by campof** [comment]
I have squashed all commits into one @daks

**Comment by daks** [comment]
merged. thanks for your work :)

**Pull request merged**
