### PR TITLE
NO_SSLv2 became an illegal option in 

### PR DESCRIPTION
**Pull request by alxwr**
Fixes the following error:

```
"options = NO_SSLv2": Illegal TLS option
```

### CODE REVIEW

**Comment by aboe76** [comment]
@alxwr any idea why the test fails to start the service?

**Review by aboe76 — COMMENTED** [review]
merge when travis is fixed

**Comment by alxwr** [comment]
@aboe76 I'll have a look next week. (aprox.)

**Review by n-rodriguez — APPROVED** [review]

**Comment by alxwr** [comment]
> merge when travis is fixed

Can't fix because of #5, I guess?

**Pull request merged**
